### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LEEBONGHAK** [42seoul-minishell/minishell#48]
- [ ] status 연결
- [ ] builtin 연결
- [ ] bracket 구현
- [ ] AND(&&), OR(||) 구현
- [ ] here_doc signal 연결 및 SIGQUIT 에러 메세지 구현
- [ ] norm
- [ ] 주석 지우기
- [ ] 여러 에러메세지 확인

**Comment by LEEBONGHAK** [comment]
- [] bracket syntax 체크를 위한 토그화 수정
